name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: clojure:tools-deps-alpine

    steps:
      - uses: actions/checkout@v1

      - name: Fetch dependencies
        run: clojure -J-Dmaven.repo.local=.m2 -Sforce

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: .m2
          key: ${{ runner.OS }}-clj-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-

      - name: Run tests
        run: clojure -J-Dmaven.repo.local=.m2 -A:test
