name: Clojure CI

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          - path: /app/.m2
          - key: ${{ runner.OS }}-build-${{ hashFiles('deps.edn') }}
      - uses: actions/checkout@v1
      - uses: ./.github/actions
