name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          tools-deps: '1.10.3.1036'

      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven

      - name: Cache Git dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gitlibs
          key: gitlibs

      - name: Run tests
        run: clojure -A:test
