name: Clojure CI

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: .m2
          key: ${{ runner.OS }}-clj-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-

      - uses: ./.github/actions
