name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'

      - name: Fetch dependencies
        run: clojure -Sforce

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: /github/home/.m2
          key: ${{ runner.OS }}-clj-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-

      - name: Run tests
        run: clojure -A:test
