name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5'

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.483'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.OS }}-clj-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-

      - name: Fetch dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: clojure -R:test -Sforce

      - name: Run tests
        run: clojure -A:test
